name: "IT test workflow"

on:
    pull_request:
        branches: [ master, stable-* ]

jobs:
    integration-tests:
        runs-on: macos-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: setup-docker
                uses: docker-practice/actions-setup-docker@1.0.8
            -   name: Build server
                run: docker build -t nextcloud-android-ci:${{github.event.number}} scripts
            -   name: Run server
                run: docker run --rm -p 80:80 -d nextcloud-android-ci:${{github.event.number}}
            -   name: Set up JDK 11
                uses: actions/setup-java@v2
                with:
                    distribution: "adopt"
                    java-version: 11
            -   name: Configure gradle
                run: |
                    mkdir -p $HOME/.gradle
                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > $HOME/.gradle/gradle.properties
                    echo "NC_TEST_SERVER_URL=http://10.0.2.2" >> $HOME/.gradle/gradle.properties
            -   name: Build gplay
                run: |
                    mkdir -p $HOME/.gradle
                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > $HOME/.gradle/gradle.properties
                    ./gradlew assembleGplayDebug
            -   name: Wait for server
                run: ./scripts/wait_for_server.sh "localhost"
            -   name: Run integration tests
                uses: reactivecircus/android-emulator-runner@v2
                with:
                    api-level: 27
                    emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -skin 500x833
                    script: ./gradlew connectedGplayDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.notAnnotation=com.owncloud.android.utils.ScreenshotTest

